//! Search tools: `glob` (match files by name pattern) and `grep` (match file
//! contents by regex), both confined to the workspace root and bounded.
//!
//! Ported from `llm-coding-tools-rig` (Apache-2.0) to rig 0.35 and reshaped to
//! Octo conventions. Stateless unit structs generated by
//! [`file_tool!`](crate::macros::file_tool); errors returned as JSON data.

use std::path::Path;

use serde::Deserialize;
use serde_json::{json, Value};

use crate::macros::file_tool;
use crate::workspace::{self, TMP_PREFIX};

/// Upper bound on files visited by one walk — a runaway-tree backstop.
const MAX_WALK_FILES: usize = 10_000;
/// Default / hard cap on `grep` matches returned.
const DEFAULT_GREP_MATCHES: usize = 200;
const MAX_GREP_MATCHES: usize = 2_000;
/// Skip grep on files larger than this (likely binary / not source).
const MAX_GREP_FILE_BYTES: u64 = 4 * 1024 * 1024;

/// Collect files under `start` (a dir within `root`) as paths relative to
/// `root`, skipping temp files, capped at [`MAX_WALK_FILES`]. Returns whether
/// the cap truncated the walk.
fn walk_files(root: &Path, start: &Path, out: &mut Vec<String>) -> bool {
    let read = match std::fs::read_dir(start) {
        Ok(r) => r,
        Err(_) => return false,
    };
    for entry in read.flatten() {
        if out.len() >= MAX_WALK_FILES {
            return true;
        }
        let name = entry.file_name();
        if name.to_string_lossy().starts_with(TMP_PREFIX) {
            continue;
        }
        let path = entry.path();
        match entry.file_type() {
            Ok(ft) if ft.is_dir() => {
                if walk_files(root, &path, out) {
                    return true;
                }
            }
            Ok(ft) if ft.is_file() => {
                if let Ok(rel) = path.strip_prefix(root) {
                    out.push(rel.to_string_lossy().into_owned());
                }
            }
            _ => {}
        }
    }
    false
}

// ── glob ────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct GlobArgs {
    /// Glob pattern matched against paths relative to the workspace root
    /// (e.g. `**/*.rs`, `src/**/mod.rs`). Supports `*`, `?`, `[...]`, `**`.
    pub pattern: String,
    /// Optional subdirectory to scope the walk; empty walks the whole root.
    #[serde(default)]
    pub path: String,
}

file_tool! {
    /// Find workspace files whose relative path matches a glob pattern.
    GlobTool, "glob",
    "Find files in the workspace whose path matches a glob pattern (`*`, `?`, \
     `[...]`, `**`), matched relative to the workspace root. Optional `path` \
     scopes the search to a subdirectory.",
    GlobArgs,
    {
        "type": "object",
        "properties": {
            "pattern": { "type": "string", "description": "glob pattern, e.g. **/*.rs" },
            "path": { "type": "string", "description": "subdirectory to scope the search" }
        },
        "required": ["pattern"]
    },
    |root, args| run_glob(&root, &args)
}

fn run_glob(root: &Path, args: &GlobArgs) -> Value {
    let pattern = match glob::Pattern::new(&args.pattern) {
        Ok(p) => p,
        Err(e) => return json!({ "error": format!("bad glob pattern: {e}") }),
    };
    let start = match workspace::resolve_in_root(root, &args.path) {
        Ok(d) => d,
        Err(e) => return json!({ "error": e.to_string() }),
    };
    let opts = glob::MatchOptions { require_literal_separator: true, ..Default::default() };
    let mut files = Vec::new();
    let truncated = walk_files(root, &start, &mut files);
    let mut matches: Vec<&String> =
        files.iter().filter(|rel| pattern.matches_with(rel, opts)).collect();
    matches.sort();
    json!({ "pattern": args.pattern, "matches": matches, "truncated": truncated })
}

// ── grep ────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct GrepArgs {
    /// Regular expression matched against each line.
    pub pattern: String,
    /// Optional subdirectory to scope the search; empty searches the whole root.
    #[serde(default)]
    pub path: String,
    /// Cap on matches returned (default 200, hard max 2000).
    #[serde(default)]
    pub max_results: Option<usize>,
}

file_tool! {
    /// Search workspace file contents line-by-line by regex.
    GrepTool, "grep",
    "Search the contents of workspace files by regular expression, returning \
     matching lines as { file, line, text }. Optional `path` scopes to a \
     subdirectory; `max_results` caps the output.",
    GrepArgs,
    {
        "type": "object",
        "properties": {
            "pattern": { "type": "string", "description": "regular expression" },
            "path": { "type": "string", "description": "subdirectory to scope the search" },
            "max_results": { "type": "integer", "description": "cap on matches (default 200)" }
        },
        "required": ["pattern"]
    },
    |root, args| run_grep(&root, &args)
}

fn run_grep(root: &Path, args: &GrepArgs) -> Value {
    let re = match regex::Regex::new(&args.pattern) {
        Ok(r) => r,
        Err(e) => return json!({ "error": format!("bad regex: {e}") }),
    };
    let start = match workspace::resolve_in_root(root, &args.path) {
        Ok(d) => d,
        Err(e) => return json!({ "error": e.to_string() }),
    };
    let limit = args.max_results.unwrap_or(DEFAULT_GREP_MATCHES).min(MAX_GREP_MATCHES);

    let mut files = Vec::new();
    walk_files(root, &start, &mut files);
    files.sort();

    let mut matches: Vec<Value> = Vec::new();
    let mut truncated = false;
    'outer: for rel in &files {
        let abs = root.join(rel);
        if let Ok(m) = std::fs::metadata(&abs) {
            if m.len() > MAX_GREP_FILE_BYTES {
                continue;
            }
        }
        // Skip non-UTF-8 (binary) files silently.
        let text = match std::fs::read_to_string(&abs) {
            Ok(t) => t,
            Err(_) => continue,
        };
        for (i, line) in text.lines().enumerate() {
            if re.is_match(line) {
                if matches.len() >= limit {
                    truncated = true;
                    break 'outer;
                }
                matches.push(json!({ "file": rel, "line": i + 1, "text": truncate_line(line) }));
            }
        }
    }
    json!({ "pattern": args.pattern, "matches": matches, "truncated": truncated })
}

fn truncate_line(line: &str) -> String {
    const MAX: usize = 500;
    if line.len() <= MAX {
        line.to_string()
    } else {
        line.chars().take(MAX).collect()
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::await_holding_lock)]

    use std::sync::MutexGuard;

    use rig::tool::Tool;

    use super::*;

    fn set_root(dir: &Path) -> MutexGuard<'static, ()> {
        let guard = crate::TEST_ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        unsafe { std::env::set_var(workspace::WORKSPACE_ENV, dir) };
        guard
    }

    fn seed(root: &Path) {
        workspace::write_atomic(root, "src/a.rs", b"fn main() {}\nlet x = 1;\n").unwrap();
        workspace::write_atomic(root, "src/util/b.rs", b"fn helper() {}\n").unwrap();
        workspace::write_atomic(root, "notes.txt", b"todo: fix the bug\n").unwrap();
    }

    #[tokio::test]
    async fn glob_matches_by_extension() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().canonicalize().unwrap();
        let _env = set_root(&root);
        seed(&root);

        let g = GlobTool.call(GlobArgs { pattern: "**/*.rs".into(), path: String::new() }).await.unwrap();
        let m: Vec<&str> = g["matches"].as_array().unwrap().iter().map(|v| v.as_str().unwrap()).collect();
        assert_eq!(m, vec!["src/a.rs", "src/util/b.rs"]);
    }

    #[tokio::test]
    async fn glob_star_does_not_cross_dirs() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().canonicalize().unwrap();
        let _env = set_root(&root);
        seed(&root);

        // A single `*` must not match across `/` (require_literal_separator).
        let g = GlobTool.call(GlobArgs { pattern: "src/*.rs".into(), path: String::new() }).await.unwrap();
        let m: Vec<&str> = g["matches"].as_array().unwrap().iter().map(|v| v.as_str().unwrap()).collect();
        assert_eq!(m, vec!["src/a.rs"]);
    }

    #[tokio::test]
    async fn grep_finds_lines() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().canonicalize().unwrap();
        let _env = set_root(&root);
        seed(&root);

        let g = GrepTool
            .call(GrepArgs { pattern: r"fn \w+".into(), path: String::new(), max_results: None })
            .await
            .unwrap();
        let hits = g["matches"].as_array().unwrap();
        assert_eq!(hits.len(), 2); // a.rs main, b.rs helper
        assert!(hits.iter().any(|h| h["file"] == "src/a.rs" && h["line"] == 1));
    }

    #[tokio::test]
    async fn grep_scoped_and_capped() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().canonicalize().unwrap();
        let _env = set_root(&root);
        seed(&root);

        let g = GrepTool
            .call(GrepArgs { pattern: ".".into(), path: "src".into(), max_results: Some(1) })
            .await
            .unwrap();
        assert_eq!(g["matches"].as_array().unwrap().len(), 1);
        assert_eq!(g["truncated"], true);
    }

    #[tokio::test]
    async fn grep_bad_regex_is_error_data() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path().canonicalize().unwrap();
        let _env = set_root(&root);
        let g = GrepTool
            .call(GrepArgs { pattern: "(".into(), path: String::new(), max_results: None })
            .await
            .unwrap();
        assert!(g["error"].as_str().unwrap().contains("bad regex"));
    }
}
