//! The file tools: `read` / `write` / `edit` / `list`, each jailed to the
//! workspace root ([`crate::workspace`]).
//!
//! Ported from `llm-coding-tools-rig` (Apache-2.0) to rig 0.35 and reshaped to
//! Octo conventions. The tools are **stateless** unit structs generated by
//! [`file_tool!`](crate::macros::file_tool) — the workspace root is read from the
//! environment on each call, so they carry no handles. Each tool's logic is a
//! small `*_impl` function; the macro supplies the `Tool` trait wiring.
//!
//! Errors are returned as JSON **data** (`{ "error": ... }`), not as `Err`, so a
//! failed call (missing file, ambiguous edit) is reported back to the model,
//! which can then adjust. This mirrors the `octo-rig` dispatch tool.

use std::path::Path;

use serde::Deserialize;
use serde_json::{json, Value};

use crate::macros::file_tool;
use crate::workspace::{self, TMP_PREFIX};

/// Cap on a single `read` so a large file can't blow the model's context. The
/// content is truncated and flagged rather than refused.
const MAX_READ_BYTES: usize = 256 * 1024;

// ── read ────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct ReadArgs {
    /// Path relative to the workspace root.
    pub path: String,
}

file_tool! {
    /// Read a UTF-8 text file from the workspace.
    ReadTool, "read",
    "Read a text file from the workspace. `path` is relative to the workspace \
     root; absolute paths and `..` escapes are rejected.",
    ReadArgs,
    {
        "type": "object",
        "properties": {
            "path": { "type": "string", "description": "path relative to the workspace root" }
        },
        "required": ["path"]
    },
    |root, args| read_file(&root, &args)
}

fn read_file(root: &Path, args: &ReadArgs) -> Value {
    match workspace::read_within(root, &args.path) {
        Ok(bytes) => {
            let truncated = bytes.len() > MAX_READ_BYTES;
            let slice = if truncated { &bytes[..MAX_READ_BYTES] } else { &bytes[..] };
            json!({
                "path": args.path,
                "content": String::from_utf8_lossy(slice),
                "bytes": bytes.len(),
                "truncated": truncated,
            })
        }
        Err(e) => json!({ "error": e.to_string() }),
    }
}

// ── write ───────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct WriteArgs {
    /// Path relative to the workspace root.
    pub path: String,
    /// Full file contents (create or overwrite).
    pub content: String,
}

file_tool! {
    /// Create or overwrite a file in the workspace (atomic).
    WriteTool, "write",
    "Create or overwrite a file in the workspace with the given content (written \
     atomically). `path` is relative to the workspace root.",
    WriteArgs,
    {
        "type": "object",
        "properties": {
            "path": { "type": "string", "description": "path relative to the workspace root" },
            "content": { "type": "string", "description": "full file contents" }
        },
        "required": ["path", "content"]
    },
    |root, args| write_file(&root, &args)
}

fn write_file(root: &Path, args: &WriteArgs) -> Value {
    match workspace::write_atomic(root, &args.path, args.content.as_bytes()) {
        Ok(_) => json!({ "path": args.path, "bytes": args.content.len() }),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

// ── edit ────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct EditArgs {
    /// Path relative to the workspace root.
    pub path: String,
    /// Exact string to find.
    pub old: String,
    /// Replacement string.
    pub new: String,
    /// Replace every occurrence instead of requiring a unique match.
    #[serde(default)]
    pub replace_all: bool,
}

file_tool! {
    /// String-replacement edit of an existing workspace file (not a diff/patch).
    EditTool, "edit",
    "Edit a workspace file by exact string replacement. `old` must occur exactly \
     once unless `replace_all` is true. Fails if `old` is absent or ambiguous. \
     `path` is relative to the workspace root.",
    EditArgs,
    {
        "type": "object",
        "properties": {
            "path": { "type": "string", "description": "path relative to the workspace root" },
            "old": { "type": "string", "description": "exact text to replace" },
            "new": { "type": "string", "description": "replacement text" },
            "replace_all": { "type": "boolean", "description": "replace all occurrences" }
        },
        "required": ["path", "old", "new"]
    },
    |root, args| edit_file(&root, &args)
}

fn edit_file(root: &Path, args: &EditArgs) -> Value {
    let bytes = match workspace::read_within(root, &args.path) {
        Ok(b) => b,
        Err(e) => return json!({ "error": e.to_string() }),
    };
    let text = match String::from_utf8(bytes) {
        Ok(t) => t,
        Err(_) => return json!({ "error": "file is not valid UTF-8; cannot edit" }),
    };
    let count = text.matches(&args.old).count();
    if count == 0 {
        return json!({ "error": "`old` not found in file" });
    }
    if count > 1 && !args.replace_all {
        return json!({
            "error": format!("`old` occurs {count} times; pass replace_all or give a unique string")
        });
    }
    let updated = if args.replace_all {
        text.replace(&args.old, &args.new)
    } else {
        text.replacen(&args.old, &args.new, 1)
    };
    match workspace::write_atomic(root, &args.path, updated.as_bytes()) {
        Ok(_) => json!({ "path": args.path, "replaced": count }),
        Err(e) => json!({ "error": e.to_string() }),
    }
}

// ── list ────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
pub struct ListArgs {
    /// Directory relative to the workspace root; empty or absent lists the root.
    #[serde(default)]
    pub path: String,
}

file_tool! {
    /// List a directory within the workspace.
    ListTool, "list",
    "List the entries of a workspace directory (name, kind, size). `path` is \
     relative to the workspace root; empty lists the root.",
    ListArgs,
    {
        "type": "object",
        "properties": {
            "path": { "type": "string", "description": "directory relative to the workspace root" }
        }
    },
    |root, args| list_dir(&root, &args.path)
}

fn list_dir(root: &Path, rel: &str) -> Value {
    let dir = match workspace::resolve_in_root(root, rel) {
        Ok(d) => d,
        Err(e) => return json!({ "error": e.to_string() }),
    };
    let read = match std::fs::read_dir(&dir) {
        Ok(r) => r,
        Err(e) => return json!({ "error": e.to_string() }),
    };
    let mut entries: Vec<Value> = Vec::new();
    for item in read.flatten() {
        let name = item.file_name().to_string_lossy().into_owned();
        if name.starts_with(TMP_PREFIX) {
            continue; // hide our atomic-write temp files
        }
        let (kind, size) = match item.metadata() {
            Ok(m) if m.is_dir() => ("dir", None),
            Ok(m) => ("file", Some(m.len())),
            Err(_) => ("unknown", None),
        };
        entries.push(json!({ "name": name, "kind": kind, "size": size }));
    }
    entries.sort_by(|a, b| a["name"].as_str().cmp(&b["name"].as_str()));
    json!({ "path": rel, "entries": entries })
}

#[cfg(test)]
mod tests {
    #![allow(clippy::await_holding_lock)]

    use std::path::Path;
    use std::sync::MutexGuard;

    use rig::tool::Tool;

    use super::*;

    fn set_root(dir: &Path) -> MutexGuard<'static, ()> {
        let guard = crate::TEST_ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        unsafe { std::env::set_var(workspace::WORKSPACE_ENV, dir) };
        guard
    }

    #[tokio::test]
    async fn write_read_edit_list_cycle() {
        let tmp = tempfile::tempdir().unwrap();
        let _env = set_root(tmp.path());

        let w = WriteTool
            .call(WriteArgs { path: "a/note.txt".into(), content: "hello world".into() })
            .await
            .unwrap();
        assert_eq!(w["bytes"], 11);

        let r = ReadTool.call(ReadArgs { path: "a/note.txt".into() }).await.unwrap();
        assert_eq!(r["content"], "hello world");
        assert_eq!(r["truncated"], false);

        let e = EditTool
            .call(EditArgs {
                path: "a/note.txt".into(),
                old: "world".into(),
                new: "octo".into(),
                replace_all: false,
            })
            .await
            .unwrap();
        assert_eq!(e["replaced"], 1);
        let r = ReadTool.call(ReadArgs { path: "a/note.txt".into() }).await.unwrap();
        assert_eq!(r["content"], "hello octo");

        let l = ListTool.call(ListArgs { path: "a".into() }).await.unwrap();
        let names: Vec<&str> =
            l["entries"].as_array().unwrap().iter().map(|e| e["name"].as_str().unwrap()).collect();
        assert_eq!(names, vec!["note.txt"]);
    }

    #[tokio::test]
    async fn edit_ambiguous_is_rejected() {
        let tmp = tempfile::tempdir().unwrap();
        let _env = set_root(tmp.path());
        WriteTool
            .call(WriteArgs { path: "d.txt".into(), content: "x x x".into() })
            .await
            .unwrap();
        let e = EditTool
            .call(EditArgs { path: "d.txt".into(), old: "x".into(), new: "y".into(), replace_all: false })
            .await
            .unwrap();
        assert!(e["error"].as_str().unwrap().contains("occurs 3 times"));
    }

    #[tokio::test]
    async fn read_missing_returns_error_data() {
        let tmp = tempfile::tempdir().unwrap();
        let _env = set_root(tmp.path());
        let r = ReadTool.call(ReadArgs { path: "nope.txt".into() }).await.unwrap();
        assert!(r["error"].is_string());
    }

    #[tokio::test]
    async fn escape_is_rejected() {
        let tmp = tempfile::tempdir().unwrap();
        let _env = set_root(tmp.path());
        let w = WriteTool
            .call(WriteArgs { path: "../evil.txt".into(), content: "x".into() })
            .await
            .unwrap();
        assert!(w["error"].as_str().unwrap().contains("escape"));
    }
}
